command_timeout = 500
format = "$directory$git_branch$time$cmd_duration$character"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "~/"

[git_branch]
symbol = "  "
style = "bold #e8ec00 inverted"
format = "on [$symbol$branch ]($style) "

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true

[package]
disabled = true
