name: Lint

on:
  push:
    paths:
      - '**/*.sh'
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          make lint
